import 'package:flutter/material.dart';

class FAQPage extends StatelessWidget {
  const FAQPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Liste des questions et réponses
    final faqs = [
      {
        "question": "Can your AI detect the tool from which the content was generated?",
        "answer": "No. AI tools are often trained with the same language models and data. That means the same text can be generated from different tools. So, it's not practically possible to detect the specific tool.",
      },
      {
        "question": "Is there a text limit for the AI detector tool?",
        "answer": "Yes. There's a word limit of 4000 per each run to ensure the best performance. You can split up the content into different parts and check it in each run. There are no limitations as to how many times you can use the detector.",
      },
      {
        "question": "Can you detect mixed text of human and AI content?",
        "answer": "Yes, our AI detector is trained with human-written as well as AI-generated texts. So, this tool can identify any text that does not have a human touch and notifies you of any mixed content along with a percentage break-up.",
      },
      {
        "question": "What percentage should I look for?",
        "answer": "It is generally recommended to aim for less than 20% AI-generated content in any given text, although ideally, the percentage should be 0. If the percentage of AI-generated content is between 20 and 50, it is likely that the text was partially or fully generated by AI. If the percentage exceeds 50%, then there is a high chance that the entire text was generated by AI.",
      },
      {
        "question": "Will my text be available online, if I check through the AI detection tool?",
        "answer": "No, we totally value your privacy. We destroy your input text as soon as the results are generated. We do not store it or publish it anywhere.",
      },
    ];

    // Derniers mots
    final finalWords = '''
As Daniela Rus, the director of MIT’s AI laboratory once said: “Dig into every industry, and you’ll find AI changing the nature of work.” And, you need a strong shield to protect yourself from the harmful effects of AI technology. Modern problems require modern solutions.
That's what our AI content detector is. Try it out for free and catch the AI content!
    ''';

    return Scaffold(
      backgroundColor: Colors.blueGrey[900],
      appBar: AppBar(
        toolbarHeight: 80,
        backgroundColor: Colors.blueGrey[900],
        elevation: 0,
        title: const Text(
          'FAQ',
          style: TextStyle(
            fontSize: 30,
            letterSpacing: 5,
            color: Colors.white,
          ),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Frequently Answered Questions',
              style: TextStyle(
                fontSize: 28,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 20),
            ...faqs.map((faq) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 20.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      faq["question"]!,
                      style: const TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                    const SizedBox(height: 10),
                    Text(
                      faq["answer"]!,
                      style: const TextStyle(
                        fontSize: 16,
                        color: Colors.white,
                      ),
                    ),
                  ],
                ),
              );
            }).toList(),
            const SizedBox(height: 30),
            const Text(
              'Final Words',
              style: TextStyle(
                fontSize: 28,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            Text(
              finalWords,
              style: const TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
