import 'package:flutter/material.dart';
import 'package:ai_detector/extension/exten.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

import '../API/detect_api.dart';
import '../constant/const.dart';
import '../model/ai_res.dart';
import 'button.dart';
import 'faq_page.dart';
import 'feature_page.dart';

class FeaturePage extends StatelessWidget {
  const FeaturePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blueGrey[900],
      appBar: AppBar(
        toolbarHeight: 80,
        backgroundColor: Colors.blueGrey[900],
        elevation: 0,
        title: const Text(
          'Features',
          style: TextStyle(
            fontSize: 30,
            letterSpacing: 5,
            color: Colors.white,
          ),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Key Features',
              style: TextStyle(
                fontSize: 28,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'Many AI detector tools are emerging in the post-GPT era with a lot of promise. That\'s why we have added a cool set of features to stay ahead of the curve. Have a look at them:',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              '1. All-in-one coverage',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'We identify content generated by any AI tool such as Chat GPT, Bing AI, Bard, etc. And, that\'s not the end. We keep on expanding our database. That means when new models and tools are introduced, we will detect them, too.',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              '2. High Accuracy',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'Tired of getting highly varied results on various GPT detectors? Our AI detector has a low false positivity rate so that you can get the most accurate results. ',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              '3. Free Tool',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'Our AI content detection tool is completely free to use. You need not enter any credit card details or sign up for spammy newsletters. Just paste the content and see the results. That\'s all. We are one of the few completely free AI content detectors out there.',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              '4. Instant Results',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'You don\'t have to waste your time by entering the content and then opening another tab to wait for the results. Our tool is designed to be super-speedy. It analyzes your text with NLP and cross-checks it with a tremendous volume of trained data to provide a result. The best part is that all these processes take place within a split second.',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              '5. Detect Mixed AI Content',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'One of the smartest ways to avoid AI content detection is by just editing the text manually. However, such hacks won\'t work with our tool. Our AI content detector not only identifies AI text but checks it out for humanisation. If it doesn\'t find that human touch in the content it will flag red no matter how much edit you have done.',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              '6. Uncompromised security',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'You don\'t need to worry about any data manipulations or transfers. Our AI detector is GDPR compliant, and we automatically delete the text after generating the results.',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
